host: localhost

server:
  port: 8087

eureka:
  instance:
    hostname: ${host}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

database:
  host: ${host}
  port: 5432
  name: svp
  username: svp_admin
  password: Vippro@

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
  zipkin:
    base-url: http://${host}:8085/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 6
        #enabled: false
      execution:
        isolation:
          #          strategy: SEMAPHORE, no thread pool but timeout handling stops to work
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
  metrics:
    rollingStats:
      timeInMilliseconds: 60000

  # More info about thread-pool configuration: https://github.com/Netflix/Hystrix/issues/1554
  threadpool:
    default:
      #Number of keep-alive threads (other threads alive for keepAliveTimeMinutes, default 1)
      coreSize: 10
      #keepAliveTimeMinutes:1

      #Maximum thread-pool size (take effect when allowMaximumSizeToDivergeFromCoreSize: true )
      #maximumSize: 5
      #allowMaximumSizeToDivergeFromCoreSize: true

      # Maximum LinkedBlockingQueue size
      # -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: 3
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 3
#  cloud:
#    stream:
#      default:
#        contentType: application/json
#      kafka:
#        binder:
#          brokers: localhost:9092
#          zkNodes: localhost:2181
#      bindings:
#        userOutput:
#          destination: test

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33
